# Generated by Django 5.0.1 on 2025-12-01 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('STOCK', 'Stock'), ('FOREX', 'Forex')], max_length=10)),
                ('api_source', models.CharField(choices=[('BINANCE', 'Binance'), ('ALPHAVANTAGE', 'Alpha Vantage')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['asset_type', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
